### ISSUE TITLE
make docker not working

### ISSUE THREAD

**Issue by Xalip** [rhasspy/rhasspy-speakers-cli-hermes#7]
I've just tried to build the docker image on my pi4.

First error that occured has been:
```
(.venv) pi@raspberrypi:~/Documents/speakersCliHermes/rhasspy-speakers-cli-hermes $ make docker
docker build . -t "rhasspy/rhasspy-speakers-cli-hermes:0.1.0" -t "rhasspy/rhasspy-speakers-cli-hermes:latest"
Sending build context to Docker daemon  14.85kB
Step 1/13 : ARG BUILD_ARCH
Step 2/13 : FROM ${BUILD_ARCH}/python:3.7-alpine
invalid reference format
make: *** [Makefile:54: docker] Error 1
```

Afterwards I had a look into the scripts folder and build-with-docker.sh and hardcoded the BUILD_ARCH argument in the dockerfile to arm64v8 and in the second run to amd64.
Both cases are throwing following error:
```
(.venv) pi@raspberrypi:~/Documents/speakersCliHermes/rhasspy-speakers-cli-hermes $ make docker
docker build . -t "rhasspy/rhasspy-speakers-cli-hermes:0.1.0" -t "rhasspy/rhasspy-speakers-cli-hermes:latest"
Sending build context to Docker daemon  14.85kB
Step 1/13 : ARG BUILD_ARCH
Step 2/13 : FROM amd64/python:3.7-alpine
3.7-alpine: Pulling from amd64/python
aad63a933944: Pull complete
f229563217f5: Pull complete
71ded8122394: Pull complete
807d0888ee2e: Pull complete
95206a02ba21: Pull complete
Digest: sha256:6787773ef4c6f728e82efd591d605e04e2b38ebcf39bf42da8d2b12527caa65b
Status: Downloaded newer image for amd64/python:3.7-alpine
 ---> 7fbc871584eb
Step 3/13 : ARG BUILD_ARCH
 ---> Running in 34b78425cda7
Removing intermediate container 34b78425cda7
 ---> 5cef56579a1f
Step 4/13 : ARG FRIENDLY_ARCH
 ---> Running in f414c09894b8
Removing intermediate container f414c09894b8
 ---> 8c2864850807
Step 5/13 : COPY etc/qemu-arm-static /usr/bin/
COPY failed: stat /var/lib/docker/tmp/docker-builder262006583/etc/qemu-arm-static: no such file or directory
make: *** [Makefile:54: docker] Error 1
```
Next I've run the build-with-docker script with no success:
```
(.venv) pi@raspberrypi:~/Documents/speakersCliHermes/rhasspy-speakers-cli-hermes/scripts $ ./build-with-docker.sh
Need to install qemu-user-static
Hit:1 http://archive.raspberrypi.org/debian buster InRelease
Get:2 http://raspbian.raspberrypi.org/raspbian buster InRelease [15.0 kB]
Hit:3 https://apt.mopidy.com buster InRelease
Hit:4 https://deb.nodesource.com/node_10.x buster InRelease
Hit:5 https://download.docker.com/linux/raspbian stretch InRelease
Hit:6 https://download.docker.com/linux/raspbian buster InRelease
Get:8 http://raspbian.raspberrypi.org/raspbian buster/main armhf Packages [13.0 MB]
Hit:7 https://packagecloud.io/headmelted/codebuilds/debian stretch InRelease
Fetched 13.0 MB in 16s (837 kB/s)
Reading package lists... Done
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package qemu-arm-static
```
In the end I used make debian and installed the package successfully.
Anyway I wanted to issue this for all other guys like me who love using docker.

**Comment by synesthesiam** [comment]
Check out the new `build-docker.sh` script. The `Dockerfile` now has a lot more comments as well.

**Comment by Xalip** [comment]
Sorry for the super late reply.

Unfortunately I'm still getting an error on running the build script:
<img width="1019" alt="image" src="https://user-images.githubusercontent.com/18552380/94960148-a3b3d300-04f2-11eb-92d7-6eef86bb5b09.png">

Do you have an idea what's the problem?

Thanks a lot

**Comment by synesthesiam** [comment]
Are you using Docker 19.03? I had to go with `docker buildx` in order to get the multi-architecture images to work right.

**Comment by Xalip** [comment]
Sure.

![image](https://user-images.githubusercontent.com/18552380/94988130-5a539a00-056b-11eb-8d60-538b167ea654.png)

**Comment by synesthesiam** [comment]
OK, what about when you run `docker buildx` by itself? If you get "docker: 'buildx' is not a docker command." then you probably need to add this to `$HOME/.docker/config.json`:

```json
{
	"experimental": "enabled"
}
```

**Comment by Xalip** [comment]
I've created a `.docker` folder, added a `config.json` and added the snippet and now I'm getting just another error...
I'm pretty sorry to keep bothering you.
<img width="831" alt="image" src="https://user-images.githubusercontent.com/18552380/98470352-56a7d880-21e5-11eb-8330-16339188478f.png">

Do you have any idea about this error? Google tells me that it's still an issue with docker buildx in some way

**Comment by synesthesiam** [comment]
It's weird, but I have to run a local Docker registry for this all to work. I use the `registry:2` container on a specific port. Then I use `DOCKER_REGISTRY=localhost:xxxx` as an environment variable to `build-docker.sh` (where `xxxx` is the registry port).

In the name of security, your local registry will not work out of the box because it's not using HTTPS. So I created a file at `/etc/docker/buildx.conf` with this in it:

```
[registry."localhost:xxxx"]
  http = true
  insecure = true
```

Then I create my builder as follows:

```sh
$ docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
$ docker buildx create --config /etc/docker/buildx.conf --use --name mybuilder
$ docker buildx use mybuilder
$ docker buildx inspect --bootstrap
```

(By the way, you have to do this every single time you reboot for some awful reason)

Finally, then you can attempt a build:

```sh
$ DOCKER_REGISTRY=localhost:xxxx ./build-docker.sh
```

As of about 6 months ago, any `curl` calls inside the container out to GitHub will fail because of HTTPS, regardless of whether `ca-certificates` is present. So I have to ensure that all the dependencies are in the `rhasspy/download` directory before building.
